In [ ]:
import numpy as pd

In [ ]:
ls=[1,2,3,4]

In [ ]:
ls

[1, 2, 3, 4]

In [ ]:
pd.array(ls)

array([1, 2, 3, 4])

In [ ]:
matrix=[[2,3,5],[7,4,2],[5,7,1]]
matrix

[[2, 3, 5], [7, 4, 2], [5, 7, 1]]

In [ ]:
pd.array(matrix)

array([[2, 3, 5],
       [7, 4, 2],
       [5, 7, 1]])

In [ ]:
pd.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
pd.arange(0.7,2)

array([0.7, 1.7])

In [ ]:
pd.zeros(3)

array([0., 0., 0.])

In [ ]:
pd.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
pd.zeros(((3,4,2)))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [ ]:
pd.ones(4)

array([1., 1., 1., 1.])

In [ ]:
pd.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
pd.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
pd.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
pd.linspace(0,4,5)

array([0., 1., 2., 3., 4.])

In [ ]:
pd.linspace(0,100,10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [ ]:
pd.random.rand(5)

array([0.42690275, 0.78143761, 0.0715497 , 0.77301973, 0.95577741])

In [ ]:
pd.random.rand(4,4)

array([[0.34070656, 0.74004594, 0.69863349, 0.11369648],
       [0.33474485, 0.21750381, 0.37991161, 0.6368337 ],
       [0.05694893, 0.6071133 , 0.62076233, 0.37421595],
       [0.07581536, 0.84233035, 0.12004038, 0.24121109]])

In [ ]:
pd.random.randn(3)

array([ 1.72892325,  0.14770478, -1.44739586])

In [ ]:
pd.random.randint(1,100)

46

In [ ]:
pd.random.randint(1,4,6)

array([2, 1, 3, 2, 3, 2])

In [ ]:
pd.arange(0,25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
ar=pd.arange(0,25)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
ar.reshape((5,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
ar.max()

24

In [ ]:
ar.min()

0

In [ ]:
ar.argmax()

24

In [ ]:
ar.argmin()

0

In [ ]:
ar.shape

(25,)

In [ ]:
ar.dtype

dtype('int64')

In [ ]:
ar[5]

5

In [ ]:
ar[1:5]

array([1, 2, 3, 4])

In [ ]:
ar[1:5]=30

In [ ]:
ar

array([ 0, 30, 30, 30, 30,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
ab=pd.array([(5,10,15),(20,25,30),(35,40,45)])
ab

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
ab[1:,:2]

array([[20, 25],
       [35, 40]])

In [ ]:
ab[:1,1:2]

array([[10]])

In [ ]:
ab > 30

array([[False, False, False],
       [False, False, False],
       [ True,  True,  True]])

In [ ]:
rs=ab < 40
rs

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True, False, False]])

In [ ]:
rs=ab < 40
ab[rs]

array([ 5, 10, 15, 20, 25, 30, 35])

In [ ]:
ab[2,:]

array([35, 40, 45])

In [ ]:
arr=pd.arange(0,25)


In [ ]:
arr.reshape((5,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
arr[1:5]=7
arr

array([ 0,  7,  7,  7,  7,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
ar1=pd.arange(0,10)
ar1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])