In [ ]:
import numpy as np

In [ ]:
ars=np.zeros(10)
ars

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
ars1=np.ones(10)
ars1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
ars2=ars1*5
ars2

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [ ]:
ars3=np.arange(10,51)
ars3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [ ]:
ars4=np.arange(10,51,2)
ars4

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [ ]:
ars5=[[0,1,2],[3,4,5],[6,7,8]]
ars5

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]

In [ ]:
np.array(ars5)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
ars6=np.eye(3)
ars6

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
ars7=np.random.rand(1)
ars7

array([0.3491121])

use numpy to generate  an array of 25 random numbers sampled from a standard normal distributiom

In [ ]:
ars8=np.random.randn(25)
ars8

array([-0.05744614, -1.44822134,  0.52381029,  1.91408141, -0.19336313,
        0.64160596, -1.09945055,  0.56132016, -0.69310728,  1.47647167,
        2.01200304, -1.07496542,  0.66058624, -1.81055295, -0.53306663,
       -0.84484069, -0.50962421,  0.45753974,  0.5135644 ,  0.86035234,
       -0.87159593,  1.14720569,  0.09777483, -0.91606677, -0.03280836])

In [ ]:
ars9=np.linspace(0,1,100)
ars9

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

Create the following matrix

In [ ]:
ars10=np.arange(1,101)
ars10
ars11=ars10.reshape(10,10)
ars12=ars11/100
ars12

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

Create an array of 20 linearly spaced pointsbetween 0 and 1

In [ ]:
ars13=np.linspace(0,1,20)
ars13

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

Replicate matrix output

In [ ]:
ars14=np.arange(1,26).reshape(5,5)
ars14

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
ars15=ars14[2:,1:]
ars15

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
ars16=ars14[3,4]
ars16


20

In [ ]:
ars17=ars14[:3,1:2]
ars17

array([[ 2],
       [ 7],
       [12]])

In [ ]:
ars18=ars14[4:]
ars18

array([[21, 22, 23, 24, 25]])

In [ ]:
ars19=ars14[3:]
ars19

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

Get the sum of all the values in matrix

In [ ]:
ars20=np.sum(ars14)
ars20

325

Get the standard deviation of the values in matrix

In [ ]:
ars21=np.std(ars14)
ars21

7.211102550927978

Get the sum of all columns in matrix

In [ ]:
ars22=np.sum(ars14,1)
ars22